app:
  name: "Golang Starter Project"
  debug: true
  environment: dev
  lang: en

key:
  token:
  refresh:
  passphrase:

host:
  name: "localhost"
  port: 5100

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  user: "root"
  name: "awesome"
  password: "secret"
