app:
  name: "Golang Starter Project"
  key:
  debug: true
  environment: dev

host:
  name: "localhost"
  port: 5100

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  user: "root"
  name: "awesome"
  password: "secret"
