openapi: 3.0.3
info:
  title: Auth
  description: The authentication uses a JWT token mechanism for signing
   method HS256
  version: v1
servers:
  - url: 'http://localhost:5100/api/v1'
    description: For local mode
  - url: 'https://sandbox.domain.com/api/v1'
    description: For staging mode
  - url: 'https://domain.com/api/v1'
    description: For production mode
paths:
  /token:
    post:
      tags:
        - Create
      summary: Create a token
      description: When we create a token, the backend will send the access token and device ID, and the response will include an automatically set cookie for device ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type : object
              required: [
                "email",
                "password"
              ]
              properties:
                email:
                  type: string
                  format: email
                  example: admin@mail.com
                password:
                  type: string
                  example: 'Password1'
          multipart/form-data:
            schema:
              type: object
              required: [
                "email",
                "password"
              ]
              properties:
                email:
                  type: string
                  format: email
                  example: admin@mail.com
                password:
                  type: string
                  example: 'Password1'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    example: {
                      "access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHFpbGEuY28uaWQiLCJleHAiOjE3MDY3MDY3NTd9.Ul-iTRe0f43Fv_BH-jsIrD0N7v8q27Dme1uSNMBT2fI",
                      "device_id": "rQUjeKHuLkPeN@f4QdPc7R7PvMGcEfztnzw7czHAoG#qY@vJYQsZ",
                    }
                  message:
                    type: string
                    example: "Generate token successfully"
        422:
          description: "Unprocessable Content"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: "bad request"
                  errors:
                    type: array
                    example: [
                     "email" : ["Email is a required field"],
                     "password" : ["Password is a required field"]
                    ]

    put:
      tags:
        - Refresh
      summary: Create a new token by device id
      description: We can attach the device ID through the request body or cookie with the key DVID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [
                "device_id"
              ]
              properties:
                device_id:
                  type: string
                  example: "rQUjeKHuLkPeN@f4QdPc7R7PvMGcEfztnzw7czHAoG#qY@vJYQsZ"
          multipart/form-data:
            schema:
              type: object
              required: [
                "device_id"
              ]
              properties:
                device_id:
                  type: string
                  example: "rQUjeKHuLkPeN@f4QdPc7R7PvMGcEfztnzw7czHAoG#qY@vJYQsZ"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                example: {
                  code : 200,
                  data : {
                    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHFpbGEuY28uaWQiLCJleHAiOjE3MDY3MDY3NTd9.Ul-iTRe0f43Fv_BH-jsIrD0N7v8q27Dme1uSNMBT2fI",
                    device_id: "29GIIQVt2RSSn@xdePvQKkq1X2Wf3$dS9Ui4sB95#facUsMyUXo3"
                  }
                }
        422:
          description: "Unprocessable Content"
          content:
            application/json:
              schema:
                type: object
                example: {
                    code: 422,
                    message: "bad request",
                    errors: {
                      "token": [ "DeviceId is a required field" ]
                    }
                  }


  
